[toolchain]
solana-version = "1.16.5"
anchor-version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart_contract = "6BoiezFL64ETgYVmNAE3w3di2qoQDEU6BMHt3Yqfe9XU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
